
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      
    - name: where am I
      run: |
        pwd
        ls target/rpm/dhis-integration/RPMS/noarch
    - name: where am I
      run: |
        pwd
        ls target/rpm/dhis-integration/RPMS/noarch
    - name: push dhis-integration to other branch
      run: |
        cd target/rpm/dhis-integration/RPMS/noarch
        mv dhis-integration-1.0-1.noarch.rpm dhis-integration-1.0-1.noarch$(date +_%d%m%Y).rpm
        ls -al
        git config --global user.email "khobatha.setetemela@gmail.com"
        git config --global user.name "khobatha"
        git init
        git branch -m master
        git add .
        git commit -m "release dhis-integration rpm "date
        git remote add github https://${{ secrets.DHIS_INTEGRATION_KEY }}@https://github.com/khobatha/bahmni-app-dhis2-integration-rpms.git
        git push -f github main
